### ISSUE TITLE
Process Decision Making Feedback Audit 1

### ISSUE THREAD

**Issue by finn-mcclusky** [24-S2-2-C-EduKATE/24-S2-2-C-EduKATE.github.io#20]

**Comment by amyWenhui** [comment]
Got useful suggestions from feedback
1. Decision Recording:
- Record key decisions using decision log templates
- Record each step of the decision process in more detail
- Record the reasons behind the choices

2. Process Improvement:
- Standardize and formalize the decision-making process
- Clearly define roles and responsibilities in the decision-making process
- Establish clear criteria for evaluating options
- Communicate with shadow regularly

3. Review and Feedback:
- Regularly collect feedback on decision implementation and results
